<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<?php
function error2exception($code,$msg,$file,$line){
    throw new ErrorException($msg);
};
set_error_handler('error2exception');

class MyEx extends Exception{
    public function __construct($message = "", $code = 0, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
    public function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub

    }
}

try {
    throw new MyEx('this is a test');
    $x = 4;
    $y = 2;
    if ($y == 0) {
        throw new ArithmeticError('Woooooo fais gaffe tu vas faire un trou dans l\'univers !');
    }
    $z = $x / $y;
    echo $z;
}
catch (MyEx $e){
    echo 'Pwet :) ';
    echo $e->getMessage();
}
catch (Exception $e){
    echo 'Pokémon "Divide by zero" capturé avec une pokéball :) ';
    echo $e->getMessage();
}
catch (Error $e){
    echo 'Pokémon "Divide by zero" capturé avec une superball :) ';
    echo $e->getMessage();
}
finally{
    echo 'c\'est fini :)';
}
?>


</body>
</html>